#!/bin/sh
[ -d /proc/1 ] || mount -t proc none /proc
[ -d /sys/kernel ] || mount -t sysfs none /sys
mount -t devtmpfs none /dev 2>/dev/null
mdev -s
mkdir -p /mnt /home
if mount -t msdos -o rw /dev/fd0 /mnt 2>/dev/null; then
    echo "Floppy Disk Detected"
    mkdir -p /mnt/data 2>/dev/null
    mount --bind /mnt/data /home 2>/dev/null
else
    echo "Booting pure RAM system"
    mount -t tmpfs none /home
fi
clear
[ -f /welcome ] && cat /welcome
cd /home
exit 0
