#!/bin/bin/sh

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
 
clear

echo "===================================================="
echo "  Welcome to project_micro Tiny Suckless Linux!         "
echo "===================================================="
echo ""

exec setsid cttyhack sh
